repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    args: ["--style=pyproject.toml", "--parallel", "--in-place"]
    additional_dependencies: [toml]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
