[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 2
column_limit = 120

[tool.isort]
line_length = 120
force_single_line = true
force_sort_within_sections = true
lexicographical = true
single_line_exclusions = ["typing"]

[tool.mypy]
[[tool.mypy.overrides]]
module = [
    "tensorflow.*",
]
ignore_missing_imports = true
